// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SceneJournal",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SceneJournal",
            targets: ["AppModule"],
            bundleIdentifier: "com.scenejournal.app",
            teamIdentifier: "8WW6Y2624W",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("SceneIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)